#ifndef RTW_HEADER_moxingxitong1_h_
#define RTW_HEADER_moxingxitong1_h_
#ifndef moxingxitong1_COMMON_INCLUDES_
# define moxingxitong1_COMMON_INCLUDES_
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "rtwtypes.h"
#include "simstruc.h"
#include "fixedpoint.h"
#include "raccel.h"
#include "rt_logging.h"
#include "dt_info.h"
#include "ext_work.h"
#include "mwmathutil.h"
#include "rt_SATURATE.h"
#include "rt_look1d.h"
#include "rt_nonfinite.h"
#endif

#include "moxingxitong1_types.h"
#define MODEL_NAME                     moxingxitong1
#define NSAMPLE_TIMES                  (2)
#define NINPUTS                        (0)
#define NOUTPUTS                       (0)
#define NBLOCKIO                       (152)
#define NUM_ZC_EVENTS                  (0)
#ifndef NCSTATES
# define NCSTATES                      (86)
#elif NCSTATES != 86
# error Invalid specification of NCSTATES defined in compiler command
#endif

#ifndef rtmGetDataMapInfo
# define rtmGetDataMapInfo(rtm)        (NULL)
#endif

#ifndef rtmSetDataMapInfo
# define rtmSetDataMapInfo(rtm, val)
#endif

typedef struct {
  real_T phimd;
  real_T DataTypeConversion;
  real_T DataTypeConversion1;
  real_T Sum;
  real_T ib[3];
  real_T StateSpace[8];
  real_T ib_j[4];
  real_T Gain;
  real_T Gain3;
  real_T Sum5[3];
  real_T StateSpace_o1[14];
  real_T StateSpace_o2[6];
  real_T Gain3_c;
  real_T Gain5;
  real_T Gain3_b;
  real_T Gain1;
  real_T Gain2;
  real_T Add1;
  real_T Gain2_o;
  real_T Gain3_bj;
  real_T Gain2_g;
  real_T Gain4;
  real_T web1;
  real_T web_psb;
  real_T web1_d;
  real_T web_psb_a;
  real_T _2H;
  real_T web_psb_d;
  real_T Ki[3];
  real_T Kv[3];
  real_T Kv_g[3];
  real_T StateSpace_h;
  real_T Vfdmax;
  real_T Sum_f;
  real_T DataTypeConversion_i;
  real_T Product1;
  real_T DataTypeConversion2;
  real_T Sum1;
  real_T StateSpace_i;
  real_T Sum_fi;
  real_T StateSpace_g;
  real_T PositiveSequenceVoltage;
  real_T Sum1_e;
  real_T Integral;
  real_T Sum4;
  real_T servomotor;
  real_T speedlimit;
  real_T Gain2_c;
  real_T web_psb_k;
  real_T web_psb_e;
  real_T web_psb_g;
  real_T web_psb_kz;
  real_T web_psb_n;
  real_T web_psb_n2;
  real_T _2H_h;
  real_T web1_p;
  real_T web3;
  real_T LookUpTable;
  real_T LookUpTable_l;
  real_T Switch3;
  real_T Sfunction;
  real_T Derivative;
  real_T LookUpTable_b;
  real_T Switch3_c;
  real_T Sfunction_c;
  real_T Derivative_a;
  real_T LookUpTable_i;
  real_T Switch3_e;
  real_T Sfunction_e;
  real_T Derivative_c;
  real_T Derivative_j;
  real_T LookUpTable_h;
  real_T LookUpTable_f;
  real_T Switch3_k;
  real_T Sfunction_n;
  real_T Derivative_o;
  real_T LookUpTable_m;
  real_T Switch3_h;
  real_T Sfunction_p;
  real_T Derivative_p;
  real_T LookUpTable_g;
  real_T Switch3_g;
  real_T Sfunction_f;
  real_T Derivative_b;
  real_T Derivative_m;
  real_T Constant[2];
  real_T TrigonometricFunction;
  real_T TrigonometricFunction1;
  real_T wewr;
  real_T TrigonometricFunction_d;
  real_T TrigonometricFunction1_o;
  real_T TrigonometricFunction2;
  real_T TrigonometricFunction3;
  real_T ira;
  real_T irb;
  real_T isa;
  real_T isb;
  real_T ira_j;
  real_T irb_b;
  real_T isa_b;
  real_T isb_j;
  real_T ira_c;
  real_T irb_n;
  real_T isa_c;
  real_T isb_a;
  real_T vdr;
  real_T vds;
  real_T vqr;
  real_T vqs;
  real_T vdr_n;
  real_T vds_n;
  real_T vqr_l;
  real_T vqs_p;
  real_T vdr_k;
  real_T vds_c;
  real_T vqr_j;
  real_T vqs_m;
  real_T Switch;
  real_T Switch1;
  real_T LookUpTable_hu;
  real_T Toff;
  real_T Step;
  real_T Gain1_d;
  real_T Memory;
  real_T Switch2;
  real_T Gain2_f;
  real_T Integrator;
  real_T Switch2_b;
  real_T Switch3_i;
  real_T Switch_m;
  real_T Gain3_f;
  real_T MultiportSwitch[3];
  real_T Sum4_m;
  real_T Product1_d[3];
  real_T Gain3_d;
  real_T MultiportSwitch_g[3];
  real_T Product1_o[3];
  real_T int_h;
  real_T Sum_j;
  real_T Switch_a;
  real_T Switch1_j;
  real_T Switch_i;
  boolean_T DataTypeConversion3;
  boolean_T DataTypeConversion2_h;
  boolean_T DataTypeConversion1_m;
  boolean_T LogicalOperator;
  boolean_T Frequency;
  boolean_T Amplitude;
  boolean_T LogicalOperator1;
  boolean_T Phase;
  boolean_T RelationalOperator;
  boolean_T RelationalOperator_p;
} BlockIO;

typedef struct {
  real_T Sfunction_DSTATE[2];
  real_T Sfunction_DSTATE_g[2];
  real_T Sfunction_DSTATE_p[2];
  real_T Sfunction_DSTATE_h[2];
  real_T Sfunction_DSTATE_a[2];
  real_T Sfunction_DSTATE_po[2];
  real_T Memory_PreviousInput;
  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative1_RWORK;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative2_RWORK;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_f;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_a;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_i;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_p;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_k;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_l;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_m;

  struct {
    real_T TimeStampA;
    real_T LastUAtTimeA;
    real_T TimeStampB;
    real_T LastUAtTimeB;
  } Derivative_RWORK_f4;

  struct {
    void *AS;
    void *BS;
    void *CS;
    void *DS;
    void *DX_COL;
    void *BD_COL;
    void *TMP1;
    void *TMP2;
    void *SWITCH_STATUS;
    void *SWITCH_STATUS_INIT;
    void *SW_CHG;
    void *CHOPPER;
    void *G_STATE;
    void *IDX_SW_CHG;
    void *Y_SWITCH;
    void *SWITCH_TYPES;
    void *IDX_OUT_SW;
  } StateSpace_PWORK;

  struct {
    void *AS;
    void *BS;
    void *CS;
    void *DS;
    void *DX_COL;
    void *BD_COL;
    void *TMP1;
    void *TMP2;
    void *SWITCH_STATUS;
    void *SWITCH_STATUS_INIT;
    void *SW_CHG;
    void *CHOPPER;
    void *G_STATE;
    void *IDX_SW_CHG;
    void *Y_SWITCH;
    void *SWITCH_TYPES;
    void *IDX_OUT_SW;
  } StateSpace_PWORK_p;

  struct {
    void *LoggedData;
  } wm_PWORK;

  struct {
    void *LoggedData;
  } Scope1_PWORK;

  struct {
    void *LoggedData;
  } Scope2_PWORK;

  struct {
    void *LoggedData;
  } Scope3_PWORK;

  struct {
    void *LoggedData;
  } Scope4_PWORK;

  struct {
    void *LoggedData;
  } Scope1_PWORK_c;

  struct {
    void *LoggedData;
  } Scope2_PWORK_k;

  struct {
    void *LoggedData;
  } Scope3_PWORK_p;

  int_T StateSpace_IWORK[4];
  int_T StateSpace_IWORK_m[4];
  int_T Enabledintegrator_MODE;
  int_T dqaxissaturation_MODE;
  int_T daxissaturation_MODE;
  int_T Saturation_MODE;
  int_T sinthrcosthr_MODE;
  int_T sinbetacosbetasinthcosth_MODE;
  int_T Rotorreferenceframe_MODE;
  int_T Stationaryreferenceframe_MODE;
  int_T Synchronousreferenceframe_MODE;
  int_T SignalGenerator_MODE;
  int_T HarmonicGenerator_MODE;
  int_T StateSpace_MODE[6];
  int_T Rotorreferenceframe_MODE_d;
  int_T Stationaryreferenceframe_MODE_k;
  int_T Synchronousreferenceframe_MODE_k;
  int_T position_MODE;
  int_T speedlimit_MODE;
  int_T Step1_MODE;
  int_T Step_MODE;
  int_T Step_MODE_e;
  int_T Step1_MODE_g;
  int8_T Enabledintegrator_SubsysRanBC;
  int8_T dqaxissaturation_SubsysRanBC;
  int8_T daxissaturation_SubsysRanBC;
  int8_T Saturation_SubsysRanBC;
  int8_T sinthrcosthr_SubsysRanBC;
  int8_T sinbetacosbetasinthcosth_SubsysRanBC;
  int8_T Rotorreferenceframe_SubsysRanBC;
  int8_T Stationaryreferenceframe_SubsysRanBC;
  int8_T Synchronousreferenceframe_SubsysRanBC;
  int8_T SignalGenerator_SubsysRanBC;
  int8_T HarmonicGenerator_SubsysRanBC;
  int8_T Rotorreferenceframe_SubsysRanBC_n;
  int8_T Stationaryreferenceframe_SubsysRanBC_b;
  int8_T Synchronousreferenceframe_SubsysRanBC_o;
  boolean_T RelationalOperator2_Mode;
  boolean_T RelationalOperator1_Mode;
  boolean_T RelationalOperator_Mode;
  boolean_T RelationalOperator_Mode_j;
} D_Work;

typedef struct {
  real_T Rotorangledtheta_CSTATE;
  real_T int_CSTATE;
  real_T int_CSTATE_k;
  real_T int_CSTATE_a;
  real_T int1_CSTATE;
  real_T int_CSTATE_i;
  real_T StateSpace_CSTATE[12];
  real_T phiqr_CSTATE;
  real_T phidr_CSTATE;
  real_T phiqs_CSTATE;
  real_T phids_CSTATE;
  real_T Rotoranglethetam_CSTATE;
  real_T Rotorspeedwm_CSTATE;
  real_T StateSpace_CSTATE_h[47];
  real_T TransferFcn_CSTATE;
  real_T TransferFcn1_CSTATE;
  real_T StateSpace_CSTATE_p;
  real_T StateSpace_CSTATE_g;
  real_T StateSpace_CSTATE_f;
  real_T Derivative_CSTATE;
  real_T Rotorspeeddeviationdw_CSTATE;
  real_T position_CSTATE;
  real_T Integrator1_CSTATE;
  real_T servomotor_CSTATE;
  real_T Integrator_CSTATE;
  real_T theta_CSTATE;
  real_T Integrator_CSTATE_e;
  real_T Integrator_CSTATE_l;
  real_T int_CSTATE_p;
} ContinuousStates;

typedef struct {
  real_T Rotorangledtheta_CSTATE;
  real_T int_CSTATE;
  real_T int_CSTATE_k;
  real_T int_CSTATE_a;
  real_T int1_CSTATE;
  real_T int_CSTATE_i;
  real_T StateSpace_CSTATE[12];
  real_T phiqr_CSTATE;
  real_T phidr_CSTATE;
  real_T phiqs_CSTATE;
  real_T phids_CSTATE;
  real_T Rotoranglethetam_CSTATE;
  real_T Rotorspeedwm_CSTATE;
  real_T StateSpace_CSTATE_h[47];
  real_T TransferFcn_CSTATE;
  real_T TransferFcn1_CSTATE;
  real_T StateSpace_CSTATE_p;
  real_T StateSpace_CSTATE_g;
  real_T StateSpace_CSTATE_f;
  real_T Derivative_CSTATE;
  real_T Rotorspeeddeviationdw_CSTATE;
  real_T position_CSTATE;
  real_T Integrator1_CSTATE;
  real_T servomotor_CSTATE;
  real_T Integrator_CSTATE;
  real_T theta_CSTATE;
  real_T Integrator_CSTATE_e;
  real_T Integrator_CSTATE_l;
  real_T int_CSTATE_p;
} StateDerivatives;

typedef struct {
  boolean_T Rotorangledtheta_CSTATE;
  boolean_T int_CSTATE;
  boolean_T int_CSTATE_k;
  boolean_T int_CSTATE_a;
  boolean_T int1_CSTATE;
  boolean_T int_CSTATE_i;
  boolean_T StateSpace_CSTATE[12];
  boolean_T phiqr_CSTATE;
  boolean_T phidr_CSTATE;
  boolean_T phiqs_CSTATE;
  boolean_T phids_CSTATE;
  boolean_T Rotoranglethetam_CSTATE;
  boolean_T Rotorspeedwm_CSTATE;
  boolean_T StateSpace_CSTATE_h[47];
  boolean_T TransferFcn_CSTATE;
  boolean_T TransferFcn1_CSTATE;
  boolean_T StateSpace_CSTATE_p;
  boolean_T StateSpace_CSTATE_g;
  boolean_T StateSpace_CSTATE_f;
  boolean_T Derivative_CSTATE;
  boolean_T Rotorspeeddeviationdw_CSTATE;
  boolean_T position_CSTATE;
  boolean_T Integrator1_CSTATE;
  boolean_T servomotor_CSTATE;
  boolean_T Integrator_CSTATE;
  boolean_T theta_CSTATE;
  boolean_T Integrator_CSTATE_e;
  boolean_T Integrator_CSTATE_l;
  boolean_T int_CSTATE_p;
} StateDisabled;

typedef struct {
  real_T StateSpace_Sf0_ZC[12];
  real_T RelationalOperator2_RelopInput_ZC;
  real_T RelationalOperator1_RelopInput_ZC;
  real_T position_IntgUpLimit_ZC;
  real_T position_IntgLoLimit_ZC;
  real_T position_LeaveSaturate_ZC;
  real_T speedlimit_UprLim_ZC;
  real_T speedlimit_LwrLim_ZC;
  real_T Sfunction_Sf0_ZC[2];
  real_T HitCrossing_HitNoOutput_ZC;
  real_T Sfunction_Sf0_ZC_n[2];
  real_T HitCrossing_HitNoOutput_ZC_h;
  real_T Sfunction_Sf0_ZC_a[2];
  real_T HitCrossing_HitNoOutput_ZC_k;
  real_T HitCrossing_HitNoOutput_ZC_p;
  real_T Sfunction_Sf0_ZC_h[2];
  real_T HitCrossing_HitNoOutput_ZC_j;
  real_T Sfunction_Sf0_ZC_ho[2];
  real_T HitCrossing_HitNoOutput_ZC_je;
  real_T Sfunction_Sf0_ZC_p[2];
  real_T HitCrossing_HitNoOutput_ZC_o;
  real_T HitCrossing_HitNoOutput_ZC_jj;
  real_T Step1_StepTime_ZC;
  real_T Step_StepTime_ZC;
  real_T Step_StepTime_ZC_d;
  real_T Step1_StepTime_ZC_p;
  real_T RelationalOperator_RelopInput_ZC;
  real_T RelationalOperator_RelopInput_ZC_l;
} ZCSignalValues;

typedef struct {
  ZCSigState StateSpace_Sf0_ZCE[12];
  ZCSigState RelationalOperator2_RelopInput_ZCE;
  ZCSigState RelationalOperator1_RelopInput_ZCE;
  ZCSigState position_IntgUpLimit_ZCE;
  ZCSigState position_IntgLoLimit_ZCE;
  ZCSigState position_LeaveSaturate_ZCE;
  ZCSigState speedlimit_UprLim_ZCE;
  ZCSigState speedlimit_LwrLim_ZCE;
  ZCSigState Sfunction_Sf0_ZCE[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE;
  ZCSigState Sfunction_Sf0_ZCE_c[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE_p;
  ZCSigState Sfunction_Sf0_ZCE_a[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE_d;
  ZCSigState HitCrossing_HitNoOutput_ZCE_o;
  ZCSigState Sfunction_Sf0_ZCE_b[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE_a;
  ZCSigState Sfunction_Sf0_ZCE_h[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE_n;
  ZCSigState Sfunction_Sf0_ZCE_br[2];
  ZCSigState HitCrossing_HitNoOutput_ZCE_n2;
  ZCSigState HitCrossing_HitNoOutput_ZCE_py;
  ZCSigState Step1_StepTime_ZCE;
  ZCSigState Step_StepTime_ZCE;
  ZCSigState Step_StepTime_ZCE_h;
  ZCSigState Step1_StepTime_ZCE_c;
  ZCSigState RelationalOperator_RelopInput_ZCE;
  ZCSigState RelationalOperator_RelopInput_ZCE_i;
} PrevZCSigStates;

struct Parameters_ {
  real_T Rotorangledtheta_IC;
  real_T web2_Gain;
  real_T int_IC;
  real_T Lad_Ll_Gain;
  real_T int_IC_g;
  real_T Lad_Llfd_Gain;
  real_T int_IC_b;
  real_T Lad_Llkd_Gain;
  real_T int1_IC;
  real_T Laq_Ll_Gain;
  real_T int_IC_e;
  real_T Laq_Llkq1_Gain;
  real_T Laq_Llkq2_Gain;
  real_T Switch_Threshold;
  real_T u_Ll_Gain;
  real_T Gain_Gain;
  real_T Gain1_Gain;
  real_T u_Ll_Gain_c;
  real_T ib_Gain;
  real_T SwitchCurrents_Value[6];
  real_T Constant3_Value;
  real_T phiqr_IC;
  real_T phidr_IC;
  real_T Llr_Gain;
  real_T phiqs_IC;
  real_T phids_IC;
  real_T Lls_Gain;
  real_T Llr1_Gain;
  real_T Llr2_Gain;
  real_T Constant_Value;
  real_T Constant1_Value;
  real_T Switch_Threshold_g;
  real_T Llr_Gain_o;
  real_T Switch1_Threshold;
  real_T Llr2_Gain_f;
  real_T Llr_Gain_l;
  real_T Llr2_Gain_g;
  real_T Rotoranglethetam_IC;
  real_T Rotorspeedwm_IC;
  real_T Constant4_Value;
  real_T ib_Gain_n;
  real_T valp_nom3_Value;
  real_T valp_nom2_Value;
  real_T SinglePhase_Value;
  real_T Switch5_Threshold;
  real_T valp_nom1_Value;
  real_T Gain_Gain_k;
  real_T valp_nom_Value;
  real_T Gain3_Gain;
  real_T P1_Value[3];
  real_T valp_nom7_Value;
  real_T p_Gain;
  real_T Gain_Gain_i[3];
  real_T Gain3_Gain_i;
  real_T T1_Value;
  real_T Gain5_Gain;
  real_T Gain7_Gain;
  real_T Gain3_Gain_h;
  real_T Gain4_Gain;
  real_T T2_Value;
  real_T Gain1_Gain_m;
  real_T Gain5_Gain_b;
  real_T T3_Value;
  real_T Gain2_Gain;
  real_T Gain6_Gain;
  real_T Gain2_Gain_k;
  real_T TransferFcn_A;
  real_T TransferFcn_C;
  real_T Gain3_Gain_n;
  real_T Gain3_Gain_e;
  real_T TransferFcn1_A;
  real_T TransferFcn1_C;
  real_T Gain2_Gain_a;
  real_T Gain1_Gain_k;
  real_T Gain4_Gain_d;
  real_T Llr1_Gain_p;
  real_T Llr3_Gain;
  real_T Constant1_Value_k;
  real_T Constant2_Value;
  real_T Constant3_Value_c;
  real_T Constant6_Value[2];
  real_T _Vb_Gain;
  real_T web1_Gain;
  real_T web_psb_Gain;
  real_T Llr1_Gain_a;
  real_T Llr3_Gain_o;
  real_T Constant4_Value_h;
  real_T Constant5_Value;
  real_T Constant6_Value_p;
  real_T Constant4_Value_i;
  real_T web1_Gain_n;
  real_T web_psb_Gain_b;
  real_T Gain1_Gain_l;
  real_T _Tb2_Gain;
  real_T F_Gain;
  real_T _2H_Gain;
  real_T web_psb_Gain_l;
  real_T Ki_Gain;
  real_T Kv_Gain;
  real_T Kv_Gain_c;
  real_T StateSpace_A;
  real_T StateSpace_C;
  real_T StateSpace_X0;
  real_T Constant1_Value_g;
  real_T StateSpace_A_c;
  real_T StateSpace_C_j;
  real_T StateSpace_X0_k;
  real_T Vfdmax1_Gain;
  real_T Constant_Value_f;
  real_T Constant3_Value_b;
  real_T Vfdmax_Gain;
  real_T StateSpace_D_e;
  real_T StateSpace_A_d;
  real_T StateSpace_C_d;
  real_T StateSpace_D_n;
  real_T StateSpace_X0_b;
  real_T Vref_Value;
  real_T Vf0ka_Value;
  real_T StateSpace_D_f;
  real_T _Vb_Gain_h;
  real_T outputformatting9_Gain;
  real_T outputformatting8_Gain;
  real_T Constant1_Value_m;
  real_T Derivative_A;
  real_T Derivative_C;
  real_T wref_Value;
  real_T nomspeed_Value;
  real_T Rotorspeeddeviationdw_IC;
  real_T units_Gain;
  real_T position_IC;
  real_T position_UpperSat;
  real_T position_LowerSat;
  real_T Pref_Value;
  real_T Switch_Threshold_k;
  real_T permanentdroop_Gain;
  real_T Integral_Gain;
  real_T Integrator1_IC;
  real_T Proportional_Gain;
  real_T servomotor_A;
  real_T servomotor_C;
  real_T speedlimit_UpperSat;
  real_T speedlimit_LowerSat;
  real_T Constant_Value_o;
  real_T turbinegain_Gain;
  real_T Integrator_IC;
  real_T beta_Gain;
  real_T Gain2_Gain_f;
  real_T Constant_Value_b;
  real_T Switch_Threshold_p;
  real_T Switch1_Threshold_o;
  real_T Rs_Ll_Gain;
  real_T web_psb_Gain_a;
  real_T N_Gain;
  real_T Rf_Llfd_Gain;
  real_T web_psb_Gain_j;
  real_T Rkd_Llkd_Gain;
  real_T web_psb_Gain_aa;
  real_T Rkq1_Llkq1_Gain;
  real_T web_psb_Gain_f;
  real_T Rkq2_Llkq2_Gain;
  real_T web_psb_Gain_e;
  real_T Rs_Ll_Gain_n;
  real_T web_psb_Gain_bb;
  real_T _Pb_Gain;
  real_T F1_Gain;
  real_T _2H_Gain_b;
  real_T theta_IC;
  real_T web1_Gain_c;
  real_T web3_Gain;
  real_T C4_Value;
  real_T com_Value;
  real_T C4_Value_c;
  real_T LookUpTable_XData[7];
  real_T LookUpTable_YData[7];
  real_T Switch3_Threshold;
  real_T Constant1_Value_k1;
  real_T Constant5_Value_p;
  real_T LookUpTable_XData_o[7];
  real_T LookUpTable_YData_l[7];
  real_T Switch3_Threshold_f;
  real_T Sfunction_P1_Size[2];
  real_T Sfunction_P1;
  real_T HitCrossing_Offset;
  real_T C4_Value_g;
  real_T Constant2_Value_h;
  real_T LookUpTable_XData_b[7];
  real_T LookUpTable_YData_g[7];
  real_T Switch3_Threshold_j;
  real_T Sfunction_P1_Size_e[2];
  real_T Sfunction_P1_i;
  real_T HitCrossing_Offset_p;
  real_T C4_Value_cw;
  real_T Constant3_Value_o;
  real_T LookUpTable_XData_g[7];
  real_T LookUpTable_YData_i[7];
  real_T Switch3_Threshold_m;
  real_T Sfunction_P1_Size_f[2];
  real_T Sfunction_P1_d;
  real_T HitCrossing_Offset_j;
  real_T HitCrossing_Offset_o;
  real_T C4_Value_b;
  real_T com_Value_p;
  real_T C4_Value_gp;
  real_T LookUpTable_XData_oj[7];
  real_T LookUpTable_YData_j[7];
  real_T Switch3_Threshold_mn;
  real_T Constant1_Value_ki;
  real_T LookUpTable_XData_c[7];
  real_T LookUpTable_YData_jm[7];
  real_T Switch3_Threshold_l;
  real_T Sfunction_P1_Size_d[2];
  real_T Sfunction_P1_e;
  real_T HitCrossing_Offset_n;
  real_T C4_Value_a;
  real_T Constant2_Value_d;
  real_T LookUpTable_XData_j[7];
  real_T LookUpTable_YData_i1[7];
  real_T Switch3_Threshold_k;
  real_T Sfunction_P1_Size_ea[2];
  real_T Sfunction_P1_l;
  real_T HitCrossing_Offset_pl;
  real_T C4_Value_i;
  real_T Constant3_Value_m;
  real_T LookUpTable_XData_m[7];
  real_T LookUpTable_YData_im[7];
  real_T Switch3_Threshold_ji;
  real_T Sfunction_P1_Size_c[2];
  real_T Sfunction_P1_i3;
  real_T HitCrossing_Offset_e;
  real_T HitCrossing_Offset_n0;
  real_T Gain_Gain_kw;
  real_T LadLmd_Gain;
  real_T phimdsat_Y0;
  real_T Vs_Value;
  real_T LaqLmq_Gain;
  real_T LadLmd_Gain_o;
  real_T phimqsat_Y0;
  real_T phimdsat_Y0_e;
  real_T Vs_Value_l;
  real_T Out1_Y0;
  real_T int_IC_gx;
  real_T Negativesequence_Value[3];
  real_T Positivesequence_Value[3];
  real_T Zerosequence_Value[3];
  real_T Negativesequence_Value_p[3];
  real_T Positivesequence_Value_e[3];
  real_T Zerosequence_Value_a[3];
  real_T harmonicA_Y0;
  real_T harmonicB_Y0;
  real_T Gain2_Gain_h;
  real_T Phase_Harmo_Value;
  real_T Gain3_Gain_p;
  real_T Phase_Harmo2_Value;
  real_T valp_nom2_Value_g;
  real_T Phase_Harmo1_Value;
  real_T Step_Time;
  real_T Step_Y0;
  real_T Step_YFinal;
  real_T Step1_Time;
  real_T Step1_Y0;
  real_T Step1_YFinal;
  real_T Gain2_Gain_kn;
  real_T Phase_Harmo_Value_h;
  real_T Gain3_Gain_ip;
  real_T Phase_Harmo2_Value_g;
  real_T valp_nom2_Value_j;
  real_T Phase_Harmo1_Value_n;
  real_T Gain4_Gain_a;
  real_T Constant4_Value_k;
  real_T Constant2_Value_l;
  real_T valp_nom7_Value_e;
  real_T Constant_Value_h;
  real_T signaltimer_Y0;
  real_T Amplitudevariation_Y0;
  real_T Frequencyvariation_Y0;
  real_T phasevariation_Y0;
  real_T LookUpTable_XData_k[9];
  real_T LookUpTable_YData_k[9];
  real_T Constant_Value_d;
  real_T Constant1_Value_a;
  real_T Constant2_Value_hp;
  real_T Constant3_Value_p;
  real_T Constant4_Value_a;
  real_T Constant5_Value_c;
  real_T Constant6_Value_e;
  real_T Constant1_Value_c;
  real_T Step1_Time_e;
  real_T Step1_Y0_o;
  real_T Step1_YFinal_i;
  real_T valp_nom5_Value;
  real_T Constant3_Value_n;
  real_T valp_nom6_Value;
  real_T Step_Time_o;
  real_T Step_Y0_c;
  real_T Step_YFinal_b;
  real_T Integrator_IC_k;
  real_T valp_nom8_Value;
  real_T valp_nom9_Value;
  real_T Gain1_Gain_n;
  real_T CONSTANT_Value;
  real_T Memory_X0;
  real_T Switch2_Threshold;
  real_T valp_nom3_Value_p;
  real_T Gain2_Gain_j;
  real_T Integrator_IC_b;
  real_T Switch_Threshold_o;
  real_T Switch_Threshold_l;
  real_T Switch1_Threshold_f;
  real_T Switch2_Threshold_a;
  real_T _Gain;
  real_T _Gain_g;
  real_T Constant_Value_hn;
  real_T vqrvdr_Y0;
  real_T vqsvds_Y0;
  real_T vqrvdr_Y0_n;
  real_T vqsvds_Y0_a;
  real_T vqrvdr_Y0_l;
  real_T vqsvds_Y0_d;
  real_T irairb_Y0;
  real_T isaisb_Y0;
  real_T irairb_Y0_f;
  real_T isaisb_Y0_b;
  real_T irairb_Y0_p;
  real_T isaisb_Y0_l;
  real_T Gain_Gain_j;
  real_T sinbetacosbetasinthcosth_Y0;
  real_T wewr_Y0;
  real_T we_Value;
  real_T web_psb_Gain_o;
  real_T sinthrcosthr_Y0;
  real_T Constant_Value_l[2];
  boolean_T wref_Value_c;
  boolean_T Vs4_Value;
  boolean_T Vs5_Value;
  boolean_T Constant_Value_i;
  boolean_T Constant3_Value_e;
  boolean_T Constant_Value_ot;
  boolean_T Constant1_Value_b;
  boolean_T Constant2_Value_h5;
  boolean_T Constant_Value_g;
  boolean_T Constant1_Value_f;
  boolean_T Constant2_Value_p;
  boolean_T Timedvariation_Y0;
};

extern Parameters rtP;
extern const char *RT_MEMORY_ALLOCATION_ERROR;
extern BlockIO rtB;
extern ContinuousStates rtX;
extern D_Work rtDWork;
extern PrevZCSigStates rtPrevZCSigState;
extern SimStruct *const rtS;
extern const int_T gblNumToFiles;
extern const int_T gblNumFrFiles;
extern const int_T gblNumFrWksBlocks;
extern rtInportTUtable *gblInportTUtables;
extern const char *gblInportFileName;
extern const int_T gblNumRootInportBlks;
extern const int_T gblNumModelInputs;
extern const int_T gblInportDataTypeIdx[];
extern const int_T gblInportDims[];
extern const int_T gblInportComplex[];
extern const int_T gblInportInterpoFlag[];
extern const int_T gblInportContinuous[];

#endif
